#:import random random.random

ShowcaseScreen:
    name: 'Encode'
    fullscreen: True
    on_parent: if args[1] and tp.current_tab == tab_fl: app.show_webencoding_method(fl)

    TabbedPanel:
        id: tp
        do_default_tab: False

        TabbedPanelItem:
            id: tab_fl
            text: 'URL'
            on_release: app.show_webencoding_method(fl)
            FloatLayout:
                CFloatLayout:
                    id: fl

                
        TabbedPanelItem:
            id: tab_box
            text: 'ENCRYPT'
            on_release: app.show_encoding_method(crypto)
            FloatLayout:
                CFloatLayout:
                    id: crypto
        
        TabbedPanelItem:
            id: tab_dec
            text: 'DECRYPT'
            on_release: app.show_decoding_method(decrypt)
            FloatLayout:
                CFloatLayout:
                    id: decrypt

<CFloatLayout@FloatLayout+BackgroundColor>
<CBoxLayout@BoxLayout+BackgroundColor>
<CGridLayout@GridLayout+BackgroundColor>
<CStackLayout@StackLayout+BackgroundColor>
<CAnchorLayout@AnchorLayout+BackgroundColor>


<BackgroundColor@Widget>
    pos_hint: {'center_x': .5, 'center_y': .5}
    size_hint: .9, .9
    canvas.before:
        Color:
            rgba: .2, .3, .4, 1
        Rectangle:
            size: self.size
            pos: self.pos
