#:kivy 1.8.0

ShowcaseScreen:
    name: 'Encode'
    fullscreen: True
    #on_parent: if args[1] and tp.current_tab == tab_fl: app.show_webencoding_method(fl)

    TabbedPanel:
        id: tp
        do_default_tab: False

        TabbedPanelItem:
            id: tab_fl
            text: 'URL'
            RelativeLayout:
                CBoxLayout:
                    orientation: 'vertical'
                    padding: (100, 100)
                    BoxLayout:
                        orientation: 'horizontal'
                        Tab1Button:
                            text: 'URL Encode'
                            on_press: app.do_url_encode(url_encode_input, url_encode_answer)
                        Tab1TextInput:
                            id: url_encode_input
                    TextInput:
                        id: url_encode_answer
                        readonly: True
                        text: 'Answer'
                        font_size: 48
                
        TabbedPanelItem:
            id: tab_box
            text: 'ENCRYPT'
            RelativeLayout:
                CBoxLayout:
                    orientation: 'vertical'
                    padding: (100, 100)
                    BoxLayout:
                        orientation: 'horizontal'
                        Tab2Button:
                            text: 'Base64'
                            on_press: app.do_base64encode(base64_encode_input, encode_answer)
                        Tab2TextInput:
                            id: base64_encode_input
                    BoxLayout:
                        orientation: 'horizontal'
                        Tab2Button:
                            text: 'MD5'
                            on_press: app.do_md5encode(md5_encode_input, encode_answer)
                        Tab2TextInput:
                            id: md5_encode_input
                    BoxLayout:
                        orientation: 'horizontal'
                        Tab2Button:
                            text: 'HEX'
                            on_press: app.do_hexencode(hex_encode_input, encode_answer)
                        Tab2TextInput:
                            id: hex_encode_input
                    TextInput:
                        id: encode_answer
                        readonly: True
                        text: 'Answer'
                        font_size: 48
        
        TabbedPanelItem:
            id: tab_dec
            text: 'DECRYPT'
            RelativeLayout:
                CBoxLayout:
                    orientation: 'vertical'
                    padding: (100, 100)
                    BoxLayout:
                        orientation: 'horizontal'
                        Tab3Button:
                            text: 'Base64'
                            on_press: app.do_base64decode(base64_decode_input, decode_answer)
                        Tab3TextInput:
                            id: base64_decode_input
                    BoxLayout:
                        orientation: 'horizontal'
                        Tab3Button:
                            text: 'MD5'
                            on_press: app.do_md5decode(md5_decode_input, decode_answer)
                        Tab3TextInput:
                            id: md5_decode_input
                    BoxLayout:
                        orientation: 'horizontal'
                        Tab3Button:
                            text: 'HEX'
                            on_press: app.do_hexdecode(hex_decode_input, decode_answer)
                        Tab3TextInput:
                            id: hex_decode_input
                    TextInput:
                        id: decode_answer
                        readonly: True
                        text: 'Answer'
                        font_size: 48

<CFloatLayout@FloatLayout+BackgroundColor>
<CBoxLayout@BoxLayout+BackgroundColor>
<CGridLayout@GridLayout+BackgroundColor>
<CStackLayout@StackLayout+BackgroundColor>
<CAnchorLayout@AnchorLayout+BackgroundColor>


<BackgroundColor@Widget>
    pos_hint: {'center_x': .5, 'center_y': .5}
    size_hint: .9, .9
    canvas.before:
        Color:
            rgba: .2, .3, .4, 1
        Rectangle:
            size: self.size
            pos: self.pos
<Tab1Button@Button>
    pos_hint: {'center_x': .7, 'center_y': .7}
    size_hint: (0.15, 0.2)
<Tab1TextInput@TextInput>
    pos_hint: {'center_x': .7, 'center_y': .7}
    size_hint:(0.6, 0.2)
    font_size: 48
    multiline: False
<Tab2Button@Button>
    pos_hint: {'center_x': .7, 'center_y': .7}
    size_hint: (0.15, 0.4)
<Tab2TextInput@TextInput>
    pos_hint: {'center_x': .7, 'center_y': .7}
    size_hint:(0.6, 0.4)
    font_size: 48
    multiline: False
<Tab3Button@Button>
    pos_hint: {'center_x': .7, 'center_y': .7}
    size_hint: (0.15, 0.4)
<Tab3TextInput@TextInput>
    pos_hint: {'center_x': .7, 'center_y': .7}
    size_hint:(0.6, 0.4)
    font_size: 48
    multiline: False
