#:kivy 1.8.0

ShowcaseScreen:
    name: 'Scratch'
    fullscreen: True
    on_parent: if args[1] : app.init_scratch(scratch_window, board, board_text, sidebar)

    BoxLayout:
        id: scratch_window
        orientation: 'horizontal'
        SFloatLayout:
            id: board
            Label:
                id: board_text
                markup: True
                text: '[color=909090]No module loaded[/color]'
        SBoxLayout:
            id: sidebar
            orientation: 'vertical'
            padding: (40, 10)
            BoxLayout:
                #padding: (0, 10)
                size_hint: (1.0, 0.2)
                TargetComponent
            BoxLayout:
                padding: (0, 10)
                size_hint: (1.0, 0.3)
                ParameterComponent
            BoxLayout:
                padding: (0, 10)
                size_hint: (1.0, 0.3)
                BodyComponent
            BoxLayout:
                padding: (0, 10)
                size_hint: (1.0, 0.2)
                TestComponent
            BoxLayout:
                padding: (0, 10)
                size_hint: (1.0, 0.2)
                RequestComponent


#<CStackLayout@StackLayout+BackgroundColor>
#<CAnchorLayout@AnchorLayout+BackgroundColor>
#<CGridLayout@GridLayout+BackgroundColor>
    
<SFloatLayout@FloatLayout+BackgroundColorLeft>
    size_hint: (0.6, 1.0)
<BackgroundColorLeft@Widget>
    pos_hint: {'center_x': .5, 'center_y': .5}
    #size_hint: 1.0, 1.0
    canvas.before:
        Color:
            rgba: .6, .3, .4, 1
        Rectangle:
            size: self.size
            pos: self.pos

<SBoxLayout@BoxLayout+BackgroundColorRight>
    size_hint: (0.3, 1.0)
<BackgroundColorRight@Widget>
    pos_hint: {'center_x': .5, 'center_y': .5}
    #size_hint: 1.0, 1.0
    canvas.before:
        Color:
            rgba: .2, .3, .4, 1
        Rectangle:
            size: self.size
            pos: self.pos

<SLabel@Label>
    size_hint: (0.25, 0.7)
<STextInput@TextInput>
    size_hint: (0.8, 0.6)
    multiline: False

<TargetComponent@Component>
    canvas.before:
        Color:
            rgba: .22, .22, .22, 1
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [20]
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint: (0.23, 0.3)
            Label:
                text: 'Target'
                size_hint: (0.35, 0.7)
        BoxLayout:
            size_hint: (1, 0.4)
            padding: [40, 20, 40, 40]
            TextInput:
                hint_text: 'Target site'

<ParameterComponent@Component>
    canvas.before:
        Color:
            rgba: .36, .36, .36, 1
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [20]
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint: (0.3, 0.2)
            Label:
                text: 'Parameter'
                size_hint: (0.35, 0.7)
        BoxLayout:
            size_hint: (1.0, 0.4)
            orientation: 'vertical'
            padding: [40, 20, 40, 40]
            TextInput:
                hint_text: 'Type'
                #size_hint: (0.8, 0.3)
            TextInput:
                hint_text: 'query'
                #size_hint: (0.8, 0.3)

<BodyComponent@Component>
    canvas.before:
        Color:
            rgba: .49, .49, .49, 1
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [20]
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint: (0.2, 0.1)
            Label:
                text: 'Body'
                size_hint: (0.25, 0.5)
        BoxLayout:
            size_hint: (1.0, 0.4)
            orientation: 'vertical'
            padding: [40, 20, 40, 40]
            BoxLayout:
                size_hint: (1.0, 0.3)
                Spinner:
                    text_autoupdate: True
                    values: 'form-data', 'json', 'xml', 'x-www-form-urlencoded'
            BoxLayout:
                padding: [0, 10, 0, 0]
                orientation: 'horizontal'
                size_hint: (1.0, 0.4)
                TextInput:
                    hint_text: 'Key'
                    #size_hint: (0.8, 0.3)
                TextInput:
                    hint_text: 'Value'
                    #size_hint: (0.8, 0.3)

<TestComponent@Component>
    canvas.before:
        Color:
            rgba: .70, .32, .32, 1
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [20]
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint: (0.27, 0.3)
            Label:
                text: 'Test for...'
                size_hint: (0.35, 0.7)
        BoxLayout:
            size_hint: (1, 0.4)
            padding: [40, 20, 40, 40]
            Spinner:
                text_autoupdate: True
                values: 'XSS (Simple)', 'XSS', 'SQLi (Simple)', 'SQLi'

<RequestComponent@Component>
    canvas.before:
        Color:
            rgba: .69, .70, .34, 1
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [20]
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint: (0.35, 0.3)
            Label:
                text: 'HTTP Request'
                size_hint: (0.35, 0.7)
        BoxLayout:
            size_hint: (1, 0.4)
            padding: [40, 20, 40, 40]
            Spinner:
                text_autoupdate: True
                values: 'GET', 'POST', 'PUT', 'HEAD', 'DELETE', 'OPTIONS'

<Component>:
    drag_rectangle: self.x, self.y, self.width, self.height
    drag_timeout: 10000000
    drag_distance: 0
    pos_hint: {'center_x': .5, 'center_y': .5}

#canvas.before:
#    Color:
#        rgba: .5, .5, .5, 1
#    Line:
#        width: 2
#        rectangle: self.x, self.y, self.width, self.height