#:import random random.random

ShowcaseScreen:
    name: 'SCRATCH BOARD'
    fullscreen: True
    on_parent: if args[1] : app.create_selector(fl)

    FloatLayout:
        CFloatLayout:
            id: fl

<CFloatLayout@FloatLayout+BackgroundColor>
<CBoxLayout@BoxLayout+BackgroundColor>
<CGridLayout@GridLayout+BackgroundColor>
<CStackLayout@StackLayout+BackgroundColor>
<CAnchorLayout@AnchorLayout+BackgroundColor>


<BackgroundColor@Widget>
    pos_hint: {'center_x': .5, 'center_y': .5}
    size_hint: 1, 1
    canvas.before:
        Color:
            rgba: .1, .1, .4, 1
        Rectangle:
            size: self.size
            pos: self.pos